<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Build.props))" Condition="Exists('$([MSBuild]::GetPathOfFileAbove(Directory.Build.props))')" />
  
  <PropertyGroup>
    <ToolkitComponentName>DependencyPropertyGenerator</ToolkitComponentName>

    <!-- This component has documentation but no interactive samples. -->
    <NoWarn>$(NoWarn);TKSMPL0014</NoWarn>
  </PropertyGroup>

  <!-- Sets this up as a toolkit component's sample project -->
  <Import Project="$(ToolingDirectory)\ToolkitComponent.SampleProject.props" />
</Project>
